#!/usr/bin/env sh

INI_FILE="/root/digitalocean.ini"

if [ ! -f $INI_FILE ]; then
    echo "ERROR: digitalocean credentials not present at $INI_FILE"
    exit 1
fi

CMD="certbot certonly --dns-digitalocean --dns-digitalocean-credentials $INI_FILE --dns-digitalocean-propagation-seconds 90"

for domain in "$@"; do
    CMD="$CMD -d $domain"
done

eval $CMD
